;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	kill-region
	markdown-exdent-or-delete
	org-beginning-of-line
	org-self-insert-command
	paredit-doublequote
	paredit-kill
	wdired-next-line
	))

(setq mc/cmds-to-run-once
      '(
	TeX-insert-backslash
	ivy-switch-buffer
	mark-page
	))
